title: Documentation
description: Site de documentation informatique
theme: just-the-docs


# Aux links for the upper right navigation
aux_links:
  "simpleDoc sur GitHub":
    - "https://github.com/medaey/simpleDoc/admindoc.github.io"